version: '2'
services:
    sherlockblog-app:
        image: sherlockblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sherlockblog-mysql:3306/sherlockblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sherlockblog-mysql:
        extends:
            file: mysql.yml
            service: sherlockblog-mysql
